# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jd_requests.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'jd_requests.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11jd_requests.proto\x12\njd_service\x1a\x1bgoogle/protobuf/empty.proto\"^\n\x19ServiceOnlineNotification\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x15\n\rservice_route\x18\x02 \x01(\t\x12\x14\n\x0cservice_port\x18\x03 \x01(\t\"2\n\x1aServiceOfflineNotification\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\"_\n\rPlatformEvent\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x15\n\revent_message\x18\x03 \x01(\t\x12\x15\n\revent_payload\x18\x04 \x01(\t2\x81\x02\n\tJDService\x12T\n\x13NotifyServiceOnline\x12%.jd_service.ServiceOnlineNotification\x1a\x16.google.protobuf.Empty\x12V\n\x14NotifyServiceOffline\x12&.jd_service.ServiceOfflineNotification\x1a\x16.google.protobuf.Empty\x12\x46\n\x11\x45mitPlatformEvent\x12\x19.jd_service.PlatformEvent\x1a\x16.google.protobuf.EmptyBHZFgithub.com/Gerardo115pp/libery-dungeon/libery_JD_service;JD_service_pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jd_requests_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/Gerardo115pp/libery-dungeon/libery_JD_service;JD_service_pb'
  _globals['_SERVICEONLINENOTIFICATION']._serialized_start=62
  _globals['_SERVICEONLINENOTIFICATION']._serialized_end=156
  _globals['_SERVICEOFFLINENOTIFICATION']._serialized_start=158
  _globals['_SERVICEOFFLINENOTIFICATION']._serialized_end=208
  _globals['_PLATFORMEVENT']._serialized_start=210
  _globals['_PLATFORMEVENT']._serialized_end=305
  _globals['_JDSERVICE']._serialized_start=308
  _globals['_JDSERVICE']._serialized_end=565
# @@protoc_insertion_point(module_scope)
