export const lf_errors = {
    ERR_PROCESSING_ERROR: "ERR_PROCESSING_ERROR",
    ERR_LOADING_ERROR: "ERR_LOADING_ERROR",
    ERR_FORBIDDEN_DUPLICATE: "ERR_FORBIDDEN_DUPLICATE",
    ERR_UNSUPPORTED_BROWSER_FEATURE: "ERR_UNSUPPORTED_BROWSER_FEATURE",
    PROGRAMMING_ERROR__MISSING_PARAMETER: "PROGRAMMING_ERROR__MISSING_PARAMETER",
    PROGRAMMING_ERROR__BROKEN_STATE: "PROGRAMMING_ERROR__BROKEN_STATE",
}