# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import MetadataServicePB.metadata_requests_pb2 as metadata__requests__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in metadata_requests_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class MetadataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckClusterPrivate = channel.unary_unary(
                '/metadata_service.MetadataService/CheckClusterPrivate',
                request_serializer=metadata__requests__pb2.IsClusterPrivate.SerializeToString,
                response_deserializer=metadata__requests__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.GetAllPrivateClusters = channel.unary_unary(
                '/metadata_service.MetadataService/GetAllPrivateClusters',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=metadata__requests__pb2.AllPrivateClustersResponse.FromString,
                _registered_method=True)
        self.TagEntities = channel.unary_unary(
                '/metadata_service.MetadataService/TagEntities',
                request_serializer=metadata__requests__pb2.TaggableEntities.SerializeToString,
                response_deserializer=metadata__requests__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.UntagEntities = channel.unary_unary(
                '/metadata_service.MetadataService/UntagEntities',
                request_serializer=metadata__requests__pb2.TaggableEntities.SerializeToString,
                response_deserializer=metadata__requests__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.GetEntitiesWithTaggings = channel.unary_unary(
                '/metadata_service.MetadataService/GetEntitiesWithTaggings',
                request_serializer=metadata__requests__pb2.TagList.SerializeToString,
                response_deserializer=metadata__requests__pb2.EntitiesByType.FromString,
                _registered_method=True)


class MetadataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckClusterPrivate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllPrivateClusters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TagEntities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UntagEntities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntitiesWithTaggings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetadataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckClusterPrivate': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckClusterPrivate,
                    request_deserializer=metadata__requests__pb2.IsClusterPrivate.FromString,
                    response_serializer=metadata__requests__pb2.BooleanResponse.SerializeToString,
            ),
            'GetAllPrivateClusters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllPrivateClusters,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=metadata__requests__pb2.AllPrivateClustersResponse.SerializeToString,
            ),
            'TagEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.TagEntities,
                    request_deserializer=metadata__requests__pb2.TaggableEntities.FromString,
                    response_serializer=metadata__requests__pb2.BooleanResponse.SerializeToString,
            ),
            'UntagEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.UntagEntities,
                    request_deserializer=metadata__requests__pb2.TaggableEntities.FromString,
                    response_serializer=metadata__requests__pb2.BooleanResponse.SerializeToString,
            ),
            'GetEntitiesWithTaggings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntitiesWithTaggings,
                    request_deserializer=metadata__requests__pb2.TagList.FromString,
                    response_serializer=metadata__requests__pb2.EntitiesByType.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metadata_service.MetadataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('metadata_service.MetadataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetadataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckClusterPrivate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata_service.MetadataService/CheckClusterPrivate',
            metadata__requests__pb2.IsClusterPrivate.SerializeToString,
            metadata__requests__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllPrivateClusters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata_service.MetadataService/GetAllPrivateClusters',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            metadata__requests__pb2.AllPrivateClustersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TagEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata_service.MetadataService/TagEntities',
            metadata__requests__pb2.TaggableEntities.SerializeToString,
            metadata__requests__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UntagEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata_service.MetadataService/UntagEntities',
            metadata__requests__pb2.TaggableEntities.SerializeToString,
            metadata__requests__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntitiesWithTaggings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metadata_service.MetadataService/GetEntitiesWithTaggings',
            metadata__requests__pb2.TagList.SerializeToString,
            metadata__requests__pb2.EntitiesByType.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
