# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metadata_requests.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'metadata_requests.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17metadata_requests.proto\x12\x10metadata_service\x1a\x1bgoogle/protobuf/empty.proto\"(\n\x10IsClusterPrivate\x12\x14\n\x0c\x63luster_uuid\x18\x01 \x01(\t\"#\n\x0f\x42ooleanResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\"6\n\x1a\x41llPrivateClustersResponse\x12\x18\n\x10private_clusters\x18\x01 \x03(\t2\xce\x01\n\x0fMetadataService\x12\\\n\x13\x43heckClusterPrivate\x12\".metadata_service.IsClusterPrivate\x1a!.metadata_service.BooleanResponse\x12]\n\x15GetAllPrivateClusters\x12\x16.google.protobuf.Empty\x1a,.metadata_service.AllPrivateClustersResponseBTZRgithub.com/Gerardo115pp/libery-dungeon/libery_metadata_service;metadata_service_pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metadata_requests_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZRgithub.com/Gerardo115pp/libery-dungeon/libery_metadata_service;metadata_service_pb'
  _globals['_ISCLUSTERPRIVATE']._serialized_start=74
  _globals['_ISCLUSTERPRIVATE']._serialized_end=114
  _globals['_BOOLEANRESPONSE']._serialized_start=116
  _globals['_BOOLEANRESPONSE']._serialized_end=151
  _globals['_ALLPRIVATECLUSTERSRESPONSE']._serialized_start=153
  _globals['_ALLPRIVATECLUSTERSRESPONSE']._serialized_end=207
  _globals['_METADATASERVICE']._serialized_start=210
  _globals['_METADATASERVICE']._serialized_end=416
# @@protoc_insertion_point(module_scope)
