# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import DownloadServicePB.download_requests_pb2 as download__requests__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in download_requests_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DownloadServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DownloadImagesBatch = channel.unary_unary(
                '/download_service.DownloadService/DownloadImagesBatch',
                request_serializer=download__requests__pb2.DownloadImagesBatchRequest.SerializeToString,
                response_deserializer=download__requests__pb2.DownloadBatchResponse.FromString,
                _registered_method=True)


class DownloadServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DownloadImagesBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DownloadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DownloadImagesBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadImagesBatch,
                    request_deserializer=download__requests__pb2.DownloadImagesBatchRequest.FromString,
                    response_serializer=download__requests__pb2.DownloadBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'download_service.DownloadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('download_service.DownloadService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DownloadService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DownloadImagesBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/download_service.DownloadService/DownloadImagesBatch',
            download__requests__pb2.DownloadImagesBatchRequest.SerializeToString,
            download__requests__pb2.DownloadBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
