# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: categories_requests.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'categories_requests.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63\x61tegories_requests.proto\x12\x12\x63\x61tegories_service\"H\n\x08\x43\x61tegory\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x66ullpath\x18\x03 \x01(\t\x12\x0e\n\x06parent\x18\x04 \x01(\t\"p\n\x11\x43\x61tegoriesCluster\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x66s_path\x18\x03 \x01(\t\x12\x17\n\x0f\x66ilter_category\x18\x04 \x01(\t\x12\x15\n\rroot_category\x18\x05 \x01(\t\"F\n\x15\x43reateCategoryRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06parent\x18\x02 \x01(\t\x12\x0f\n\x07\x63luster\x18\x03 \x01(\t\"&\n\x16\x43reateCategoryResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\"\n\x12GetCategoryRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"+\n\x1bGetCategoriesClusterRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"E\n\x13GetCategoryResponse\x12.\n\x08\x63\x61tegory\x18\x01 \x01(\x0b\x32\x1c.categories_service.Category\"V\n\x1cGetCategoriesClusterResponse\x12\x36\n\x07\x63luster\x18\x01 \x01(\x0b\x32%.categories_service.CategoriesCluster2\xd7\x02\n\x11\x43\x61tegoriesService\x12g\n\x0e\x43reateCategory\x12).categories_service.CreateCategoryRequest\x1a*.categories_service.CreateCategoryResponse\x12^\n\x0bGetCategory\x12&.categories_service.GetCategoryRequest\x1a\'.categories_service.GetCategoryResponse\x12y\n\x14GetCategoriesCluster\x12/.categories_service.GetCategoriesClusterRequest\x1a\x30.categories_service.GetCategoriesClusterResponseBXZVgithub.com/Gerardo115pp/libery-dungeon/libery_categories_service;categories_service_pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'categories_requests_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZVgithub.com/Gerardo115pp/libery-dungeon/libery_categories_service;categories_service_pb'
  _globals['_CATEGORY']._serialized_start=49
  _globals['_CATEGORY']._serialized_end=121
  _globals['_CATEGORIESCLUSTER']._serialized_start=123
  _globals['_CATEGORIESCLUSTER']._serialized_end=235
  _globals['_CREATECATEGORYREQUEST']._serialized_start=237
  _globals['_CREATECATEGORYREQUEST']._serialized_end=307
  _globals['_CREATECATEGORYRESPONSE']._serialized_start=309
  _globals['_CREATECATEGORYRESPONSE']._serialized_end=347
  _globals['_GETCATEGORYREQUEST']._serialized_start=349
  _globals['_GETCATEGORYREQUEST']._serialized_end=383
  _globals['_GETCATEGORIESCLUSTERREQUEST']._serialized_start=385
  _globals['_GETCATEGORIESCLUSTERREQUEST']._serialized_end=428
  _globals['_GETCATEGORYRESPONSE']._serialized_start=430
  _globals['_GETCATEGORYRESPONSE']._serialized_end=499
  _globals['_GETCATEGORIESCLUSTERRESPONSE']._serialized_start=501
  _globals['_GETCATEGORIESCLUSTERRESPONSE']._serialized_end=587
  _globals['_CATEGORIESSERVICE']._serialized_start=590
  _globals['_CATEGORIESSERVICE']._serialized_end=933
# @@protoc_insertion_point(module_scope)
